from collections import OrderedDict

TRAINING_VIEWS = OrderedDict([
    ('A/B Testing', 'onboarding/training/ab-testing.html'),
    ('API Endpoints', 'onboarding/training/api-endpoints.html'),
    ('Billing and Django', 'onboarding/training/billing.html'),
    ('Client vs. Server-side Implementations', 'onboarding/training/client-server.html'),
    ('Debugging Techniques', 'onboarding/training/debugging.html'),
    ('Funnels 101', 'onboarding/training/funnels101.html'),
    ('Funnels Deep Dive', 'onboarding/training/funnels-deep-dive.html'),
    ('Identity Management 101', 'onboarding/training/identity-management101.html'),
    ('Identity Management Deep Dive', 'onboarding/training/identity-management-deep-dive.html'),
    ('Identifying and Reporting on Bugs', 'onboarding/training/bugs.html'),
    ('Intro to Dungeon Master', 'onboarding/training/dungeon-master.html'),
    ('Intro to Music Finder', 'onboarding/training/music-finder.html'),
    ('Intro to Platform', 'onboarding/training/platform.html'),
    ('Lesser Used Reports Deep Dive', 'onboarding/training/lesser-reports-deep-dive.html'),
    ("Mixpanel Demo, So what's all the fuss about?", 'onboarding/training/demo.html'),
    ('Mixpanel in Action', 'onboarding/training/mixpanel-action.html'),
    ('Mobile Attribution', 'onboarding/training/mobile-attribution.html'),
    ('Music Finder', 'onboarding/training/music-finder.html'),
    ('Notifications 101', 'onboarding/training/notifications101.html'),
    ('Notifications Deep Dive', 'onboarding/training/notifications-deep-dive.html'),
    ('Paired Ticketing', 'onboarding/training/paired-ticketing.html'),
    ('People Overview', 'onboarding/training/people-overview.html'),
    ('People vs. Engagement', 'onboarding/training/people-vs-engagement.html'),
    ('People vs. Engagement Deep Dive', 'onboarding/training/people-deep-dive.html'),
    ('Processes Training', 'onboarding/training/processes.html'),
    ('Retention 101', 'onboarding/training/retention101.html'),
    ('Retention Deep Dive', 'onboarding/training/retention-deep-dive.html'),
    ('Segmentation 101', 'onboarding/training/segmentation101.html'),
    ('Segmentation Deep Dive', 'onboarding/training/segmentation-deep-dive.html'),
    ('Service Cloud Run Through', 'onboarding/training/service-cloud.html'),
    ('Slack Training', 'onboarding/training/slack.html'),
    ('Super Properties', 'onboarding/training/super-properties.html'),
    ('Terminal and Scripts', 'onboarding/training/terminal.html'),
    ('Training on Diversity', 'onboarding/training/diversity.html'),
    ('Webinar', 'onboarding/training/webinar.html'),
    ('Welcome to Mixpanel Support!', 'onboarding/training/welcome.html'),
])
