from collections import OrderedDict

TRAINING_VIEWS = OrderedDict([
    ('A/B Testing', 'onboarding/training/ab-testing.html'),
    ('API Endpoints', 'onboarding/training/api-endpoints.html'),
    ('Bad News Bears', 'onboarding/training/no-info-training.html'),
    ('Client vs. Server-side Implementations', 'onboarding/training/client-server.html'),
    ('Debugging Techniques', 'onboarding/training/debugging.html'),
    ('Funnels 101', 'onboarding/training/funnels101.html'),
    ('Funnels Deep Dive', 'onboarding/training/funnels-deep-dive.html'),
    ('Identity Management 101', 'onboarding/training/identity-management101.html'),
    ('Identity Management Deep Dive', 'onboarding/training/identity-management-deep-dive.html'),
    ('Identifying and Reporting on Bugs', 'onboarding/training/bugs.html'),
    ('Insights 101', 'onboarding/training/no-info-training.html'),
    ('Intro to Music Finder', 'onboarding/training/music-finder.html'),
    ('Intro to Signal', 'onboarding/training/no-info-training.html'),
    ('Intro to Zendesk', 'onboarding/training/no-info-training.html'),
    ('Lesser Used Reports Deep Dive', 'onboarding/training/lesser-reports-deep-dive.html'),
    ('Messages 101', 'onboarding/training/notifications101.html'),
    ('Messages Deep Dive', 'onboarding/training/notifications-deep-dive.html'),
    ('Mixpanel in Action', 'onboarding/training/mixpanel-action.html'),
    ('Mobile Attribution', 'onboarding/training/mobile-attribution.html'),
    ('Music Finder', 'onboarding/training/music-finder.html'),
    ('Paired Ticketing', 'onboarding/training/paired-ticketing.html'),
    ('People Overview', 'onboarding/training/people-overview.html'),
    ('People vs. Engagement', 'onboarding/training/people-vs-engagement.html'),
    ('People vs. Engagement Deep Dive', 'onboarding/training/people-deep-dive.html'),
    ('Processes', 'onboarding/training/processes.html'),
    ('QBQ', 'onboarding/training/no-info-training.html'),
    ('Retention', 'onboarding/training/retention101.html'),
    ('Segmentation', 'onboarding/training/segmentation-deep-dive.html'),
    ('Service Cloud Run Through', 'onboarding/training/service-cloud.html'),
    ('Super Properties', 'onboarding/training/super-properties.html'),
    ('Terminal and Scripts', 'onboarding/training/terminal.html'),
    ('Training on Diversity', 'onboarding/training/diversity.html'),
    ('Webinar', 'onboarding/training/webinar.html'),
    ('Welcome to Mixpanel Support!', 'onboarding/training/welcome.html'),
])
